### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by tohti0115** [anthonyweidai/SvANet#14]
@anthonyweidai Hello, I have the following problem, how can I fix it
`********************** Training and Validating 1 **********************
100%|████████████████████████████████| 649/649 [08:18<00:00,  1.30it/s]
  0%|                                           | 0/25 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/SvANet-main/main.py", line 182, in <module>
    MyTrain.training()
  File "/root/autodl-tmp/SvANet-main/main.py", line 138, in training
    self.MyTrainer.run(Round, Split)
  File "/root/autodl-tmp/SvANet-main/lib/trainer/trainerEngine.py", line 76, in run
    self.training(Epoch)
  File "/root/autodl-tmp/SvANet-main/lib/trainer/trainerEngine.py", line 117, in training
    self.validating(Epoch)
  File "/root/miniconda3/envs/svanet/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/SvANet-main/lib/trainer/trainerEngine.py", line 131, in validating
    Loss, FinalPredLabel = mixCriterion(self.opt, self.LossFn, 
  File "/root/autodl-tmp/SvANet-main/lib/loss_fn/utils.py", line 7, in mixCriterion
    return LossFn(Input, Prediction, Target), Prediction
  File "/root/miniconda3/envs/svanet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/svanet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/SvANet-main/lib/loss_fn/segmentation/segCrossEntropy.py", line 58, in forward
    TotalLoss = self.computeLoss(
  File "/root/autodl-tmp/SvANet-main/lib/loss_fn/segmentation/segCrossEntropy.py", line 24, in computeLoss
    _,y_h, y_w = TargetMask.shape
ValueError: not enough values to unpack (expected 3, got 1)
`

**Comment by anthonyweidai** [comment]
Do you use 3D image data? We only support 2D image for now.

**Comment by tohti0115** [comment]
@anthonyweidai I used ISIC 2018 Dataset
