### ISSUE TITLE
Using tinyObjectsValidation.py for reasoning will result in an error，Can anyone give me some guidance?

### ISSUE THREAD

**Issue by GOfBlue** [anthonyweidai/SvANet#6]
Traceback (most recent call last):
  File "/mnt/data12t/gyc_data_new/SvANet-main/tools/tinyObjectsValidation.py", line 12, in <module>
    from lib.data import getMyDataset
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/data/__init__.py", line 2, in <module>
    from .mydatasetReg import getMyDataset
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/data/mydatasetReg.py", line 36, in <module>
    importModule(__file__, SkipFolder=['collate_fn', 'process', 'sampler', 'tools'])
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/utils/utils.py", line 14, in importModule
    SubFolds.extend(next(os.walk(RegisterPath))[1]) # return folder only list
StopIteration
ERROR conda.cli.main_run:execute(49): `conda run python /mnt/data12t/gyc_data_new/SvANet-main/tools/tinyObjectsValidation.py` failed. (See above for error)

**Comment by anthonyweidai** [comment]
You should move the tinyObjectsValidation.py to the working dir.
