### ISSUE TITLE
推理的时候报错

### ISSUE THREAD

**Issue by GOfBlue** [anthonyweidai/SvANet#7]
/usr/local/anaconda3/condabin/conda run -n svanet --no-capture-output python /mnt/data12t/gyc_data_new/SvANet-main/tools/tinyObjectsValidation.py 
Traceback (most recent call last):
  File "/mnt/data12t/gyc_data_new/SvANet-main/tools/tinyObjectsValidation.py", line 12, in <module>
    from lib.data import getMyDataset
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/data/__init__.py", line 2, in <module>
    from lib.data.mydatasetReg import getMyDataset
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/data/mydatasetReg.py", line 36, in <module>
    importModule(__file__, SkipFolder=['collate_fn', 'process', 'sampler', 'tools'])
  File "/mnt/data12t/gyc_data_new/SvANet-main/lib/utils/utils.py", line 13, in importModule
    SubFolds.extend(next(os.walk(RegisterPath))[1]) # return folder only list
StopIteration
ERROR conda.cli.main_run:execute(49): `conda run python /mnt/data12t/gyc_data_new/SvANet-main/tools/tinyObjectsValidation.py` failed. (See above for error)

Process finished with exit code 1
有大佬可以解答一下吗？

**Comment by anthonyweidai** [comment]
#6

**Comment by GOfBlue** [comment]
谢谢作者，问题已解决。我的服务器是linux，可能您是有些代码路径是和windows适配，所以我对一些导包的代码进行了重写，导包问题已解决，推理已经可以正常进行了。

**Comment by anthonyweidai** [comment]
> 谢谢作者，问题已解决。我的服务器是linux，可能您是有些代码路径是和windows适配，所以我对一些动态导包的代码进行了重写，导包问题已解决，推理已经可以正常进行了。

We have tested our code on both Windows and Ubuntu (Linux) systems, and both support our program. Thank you for your suggestions.
